### ISSUE TITLE
【Backend】根據 Ken 的 Code 進行重構與修改

### ISSUE THREAD

**Issue by ping-yee** [Game-as-a-Service/The-Message#19]
**Task List**
- [x] database 的資料庫連接組態設定應該會改放在 config 裡面
- [x] db.go => database.go
- [x] 把 gameRepository & playerRepository 改成 game 與 player，之前誤寫，這兩個東西應該是  View Model (Domain Model)，拿來放輸出格式 (Domain) 與定義 Interface
- [x] 如果 request 資料夾裡面定義的是 View Model (Domain Model)，我會把他跟第三點進行 Merged
- [x] Service 把 StartGame() 整合近 Handler，其他 method 會留在 Service 裡面
- [ ] enums 改成放到資料庫內
- [x] Test 資料夾需要想一下
- [x] 無法進行 Migrate，可能需要修復一下
- [x] 整合我當初取得 .env data 功能
- [x] I got an error

```log
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2023/10/12 - 15:59:43 | 400 |      271.75µs |             ::1 | POST     "/api/v1/games"
```

**Comment by linycken013127** [comment]
[#35](https://github.com/Game-as-a-Service/The-Message/pull/35) 
本次 PR 完成以下項目，關於最後一個 Error 的部分，我這邊環境沒有發生相關狀況，再幫我看看有沒有問題～

**Task List**
- [x] database 的資料庫連接組態設定應該會改放在 config 裡面
- [x] db.go => database.go
- [ ] 把 gameRepository & playerRepository 改成 game 與 player，之前誤寫，這兩個東西應該是  View Model (Domain Model)，拿來放輸出格式 (Domain) 與定義 Interface
- [ ] 如果 request 資料夾裡面定義的是 View Model (Domain Model)，我會把他跟第三點進行 Merged
- [ ] Service 把 StartGame() 整合近 Handler，其他 method 會留在 Service 裡面
- [ ] enums 改成放到資料庫內
- [x] Test 資料夾需要想一下
- [x] 無法進行 Migrate，可能需要修復一下
- [x] 整合我當初取得 .env data 功能
- [ ] I got an error
