### ISSUE TITLE
【Backend】完成初版「風聲遊戲」/ All Task List

### ISSUE THREAD

**Issue by ping-yee** [Game-as-a-Service/The-Message#23]
### 遊戲元件

- [x] https://github.com/Game-as-a-Service/The-Message/issues/38
- [ ] 查看目前遊戲狀況API
- [ ] 查看當前回合資訊 SSE
- [ ] 刪除遊戲

### 玩家元件

- [x] 查看玩家資訊
- [ ] https://github.com/Game-as-a-Service/The-Message/issues/50
- [x] https://github.com/Game-as-a-Service/The-Message/issues/70
- [ ] 玩家選擇是否接受卡牌

### 卡牌元件（Duplicate）

- [ ] 出功能牌
  - [ ] 玩家查看目前可用卡牌資訊API
  - [x] https://github.com/Game-as-a-Service/The-Message/issues/70
  - [ ] 實做功能牌(9種，可分階段做)
 
- [ ] 選擇傳遞情報卡階段
  - [x] https://github.com/Game-as-a-Service/The-Message/issues/92
  - [x] https://github.com/Game-as-a-Service/The-Message/issues/95

## Testing（需更完善）

- [ ] Unit Test
- [ ] End-to-End Test

## API 文件

- [ ] API Doc version 0.1
- [ ] API Doc version 0.2
- [ ] API Doc 架在 CD

```
http://127.0.0.1:8080/swagger/index.html
```

## Database ERD

- [ ] ERD version 0.1
- [ ] ERD version 0.2

## 大平台
- [x] https://github.com/Game-as-a-Service/The-Message/issues/81

**Comment by linycken013127** [comment]
sprint1 完成
