### ISSUE TITLE
【DevOps】完成初版「風聲遊戲」/ All Task List

### ISSUE THREAD

**Issue by ping-yee** [Game-as-a-Service/The-Message#78]
## CI

- [x] 前端 CI Testing
- [x] 後端 CI Unit Testing 
- [x] 後端 CI End-to-End Testing 

## CD

- [ ] 前端 React Deploy
- [ ] 前端 CD
- [ ] 後端 CD
- [ ] 同步專案進度 Survey
- [ ] Zeabur Survey

**Comment by linycken013127** [comment]
sprint1 完成
